name: vivacity_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 4.0.4
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.6.0
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/initial_carousel/
    - assets/login/
    - assets/home/
    - assets/lugares/
    

