name: vivacity_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 4.0.4
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.6.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.2.2
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/initial_carousel/
    - assets/login/
    - assets/home/
    - assets/eventos/
    - assets/eventos/melendi/
    - assets/favourites/
    - data/hoteles.json
    - assets/map_style.json
    - data/shopping.json
    - assets/lugares/
    

